#!/usr/bin/env bash
# Installing a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 141928-web-01 3.86.18.22:80 check\n\tserver 141928-web-02 100.25.47.196:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
