#!/usr/bin/env bash
# Installing a load balancer
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 93296-web-01 35.153.193.4:80 check\n\tserver 93296-web-02 100.25.138.224:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
