#!/usr/bin/env bash
#A script
pid_file="/var/run/my_process.pid"
log_file="/tmp/my_process"

start() {
    if [ -f "$pid_file" ]; then
        echo "Error: manage_my_process is already running."
        exit 1
    fi
    
    ./manage_my_process &

    echo "$!" > "$pid_file"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "Error: manage_my_process is not running."
        exit 1
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

